### PR TITLE
Add extra setup details to README

### PR DESCRIPTION
**Pull request by djm**
Hi Jonathon!

I was just getting set up to play around with Ping CRM to see how Inertia feels but I haven't used PHP in years, so I tripped up on a couple of missing steps in the README which are probably obvious to seasoned vets – but not so much me. 

Hopefully they'll help someone else; let me know if they're not correct.

### CODE REVIEW

**Comment by Juhlinus** [comment]
While I see where you're coming from I wouldn't say that this should be needed.

The reason for this is because setting up PingCRM is any different to start using any other Laravel app.

If you're curious about how to run a Laravel app, then you should have a look at the docs for Laravel.
https://laravel.com/docs/5.8/installation#installing-laravel

If you wish to know what PHPUnit is and how to use it, then you should check out PHPUnits docs.
https://phpunit.de/getting-started/phpunit-8.html

My point being that it should not fall on each package developer to educate the developers on how to use anything else but the package/project itself. Otherwise we wind up with bloated README files, in my opinion.

Just my 2 cents.

**Comment by djm** [comment]
Hi Linus! I can see definitely see that side of it but I would question:

* why include the other step-by-step instructions but miss a step?
* how would a newcomer know this was a Laravel app?

If the idea is to spread Inertia.js idioms outside of the Laravel/PHP community then a good step would be to make the project welcoming to all, and that means making it easy for everyone to get started so they can see if it's even worth their time. Currently this project is the fastest way to see what it's capable of, unless I've missed something else.

If the desire is for Inertia.js to stay within the PHP ecosystem, then I'd wholly understand.

**Comment by djm** [comment]
Another option is to drop the phpunit doc change but keep the serve instruction, as passers-by probably won't care about testing.

**Comment by reinink** [comment]
Thanks for this @djm! I opted to leave out the phpunit note, but left the web server note. Thanks! 💪

**Pull request merged**
