### PR TITLE
Upgrade to tailwind v1.0

### LINKED ISSUE #20: Update to Tailwind v1
Tailwind v1.0.0 was released!.. please update.

### PR DESCRIPTION
**Pull request by gzhihao**
This PR resolves #20 

I compared the look and feel with the previous version side by side, almost identical except a few minor things:
- Width difference (the default max-width scale is a bit different between two versions) 
- Font size (It's a little bigger than previous version)

I preserve the colors naming and add them to config. I can follow up and align with the new naming scheme in a separate commit or PR. Just let me know.

### CODE REVIEW

**Comment by reinink** [comment]
Amazing! Great start.

One text size issue is that `text-base` has been renamed to `text-md` in the layout:

https://github.com/gzhihao/pingcrm/blob/master/resources/js/Shared/Layout.vue#L18

Also, if you'd be up for it, I'd love to switch the colours over to the default Tailwinds, and remove all the extended colours from this config. Would you be up for doing that? 

I'll review this in more detail later.

**Comment by gzhihao** [comment]
Great! Happy to work on it.
Will tweak the text a bit, and include the colours change in this PR.

**Comment by gzhihao** [comment]
@reinink I've added a commit to removed the extended colours and mapped them back to tailwind defaults. 

As 1.0's colour scheme is changed, the app looks quite different. (see attachments for the comparison) I could tune the colours and style a bit, but thought this PR is mainly on upgrade tailwind. So I followed the [colours upgrade guide](https://tailwindcss.com/docs/upgrading-to-v1/#1-update-any-usage-of-text-bg-border-color-classes) to map the colours w/o any tweak. Quite a lot files are changed, pls review them and let me know if anything I need to follow up. 

Cheers!

**Before**
pingcrm_before_switch

**After**
pingcrm_after_switch

**Comment by gzhihao** [comment]
Haha, I tried some minor tweaks on the background colours (in the 3rd commit).

It looks a bit better - here is the screenshot

**After tweak**

pingcrm_tweak

**Comment by gzhihao** [comment]
@reinink what's your take on the color settings? Let me know if there is anything I can do to move this PR forward.

**Comment by reinink** [comment]
@gzhihao Hey there! I hope to get to this soon. I think I'm going to pull your branch down and mess with it. Stay tuned.

**Comment by adibhanna** [comment]
Thank you for working on this PR @gzhihao & @reinink! 
Any news on when this will be merged?

**Comment by imknight** [comment]
don't forget the flash message should turn bg-green to bg-green-500

**Pull request merged**
