### PR TITLE
Upgrade Laravel 9.x (#1)

### PR DESCRIPTION
**Pull request by treckstar**
* fix: upgrade & remove unused dependencies

* fix: search for contacts assertion mismatch

* fix: wrong AssertableInertia type given

### CODE REVIEW

**Comment by treckstar** [comment]
Added in `vite` + `laravel-vite`
Removed `mix`. 
I'm not an expert with `ssr` but I added several commands in the `package.json` to try out.
Learned a bunch about `laravel`, `inertia`, etc doing this, thanks for the this demo!

**Comment by treckstar** [comment]
Reverted previous changes, updated everything using the latest Laravel Breeze + Vue & SSR code.  Seems to be working great. Use `npm run build` to compile the `ssr.mjs` file and then `npm run start` to start the service.

**Comment by treckstar** [comment]
### Test demo site: 
**https://testing.my.aggressivecache.com/**

**Comment by treckstar** [comment]
I can see that this PR may need updated with Inertia 1.0, if there is any interest in that let me know. 😁🫡

**Comment by jessarcher** [comment]
Thanks! Ended up letting Shift handle this in #209.

**Pull request closed without merging**
